version: '3.1'

services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: acm_mongo
  acm_app:
    build: .
    container_name: acm_app
    restart: always
    ports:
      - 8080:8080
    depends_on: 
      - mongo